name: Deploy to production

on:
  push:
    branches: master

jobs:
  lint:
    uses: "./.github/workflows/lint.yml"

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    environment: production
    concurrency: production

    steps:
      - name: Post to webhook
        run: curl --fail-with-body -X POST ${{ secrets.DEPLOYER_WEBHOOK }}/${{ github.event.repository.name }}
